# Generated by Django 4.1 on 2022-11-10 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductMain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.TextField(max_length=30)),
                ("description", models.TextField(max_length=100)),
                ("price", models.FloatField()),
                ("unique_code", models.IntegerField(unique=True)),
                (
                    "size",
                    models.CharField(
                        choices=[("10", "10"), ("20", "20"), ("30", "30")], max_length=2
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("high", "high"),
                            ("low", "low"),
                            ("medium", "medium"),
                        ],
                        max_length=6,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="productImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projectApp.productmain",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("red", "red"),
                            ("blue", "blue"),
                            ("green", "green"),
                            ("black", "black"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projectApp.productmain",
                    ),
                ),
            ],
        ),
    ]
