# Generated by Django 4.1 on 2022-11-11 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projectApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcolor",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="color",
                to="projectApp.productmain",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="projectApp.productmain",
            ),
        ),
    ]
